### ISSUE TITLE
Could not find executable pandoc-include

### ISSUE THREAD

**Issue by axelkennedal** [DCsunset/pandoc-include#36]
I know that Issue #1 seems very similar to this, however I have followed the solution there and it does not work for me.

## Problem
When trying to use pandoc-include like ` pandoc .\Book.md --filter pandoc-include -o book.pdf` I get the error 
`Error running filter pandoc-include:
Could not find executable pandoc-include`

## Background
I have done the following:
1. Install Python from https://www.python.org/downloads/
2. Run `pip install --upgrade pandoc`,  `pip install pandoc-include`
3. Moved pandoc-include from the Roaming folder it was installed in (`C:\Users\myuser\AppData\Roaming\Python\Python311\site-packages`), to the same folder as where pandoc is installed in (`C:\Users\myuser\AppData\Local\Programs\Python\Python311\Lib\site-packages`)
4. Made sure that pandoc-include is in the path variable: running `echo $env:PATH` returns my path, which contains `C:\Users\myuser\AppData\Local\Programs\Python\Python311\Lib\site-packages`

My pandoc version is 2.3 and pandoc-include is 1.2.0.

**Comment by DCsunset** [comment]
Are you able to run pandoc-include directly from command line? If it still says "Could not find executable pandoc-include", then it may be added to the path correctly.

**Comment by axelkennedal** [comment]
No I am not, even though I have installed pandoc-include as in the README:
![image](https://github.com/DCsunset/pandoc-include/assets/8863787/66bee193-30c6-411f-a886-d251eef652c3)

![image](https://github.com/DCsunset/pandoc-include/assets/8863787/d2c9cd11-75e3-4c8a-989e-86894835a67e)

**Comment by kingkaos** [comment]
Did you solve the problem?
I'm struggling using `pandoc-include` within a docker container.

I installed `pandoc-include` using `pipx`. For debugging I run pandoc from the container:

```
root@9b0c75a2e4b3:/app# pandoc --filter /root/.local/bin/pandoc-include demo.md
[INFO] including file 'demo2.md'... ok
Error running filter pandoc-include:
Could not find executable pandoc-include

Traceback (most recent call last):
  File "/root/.local/bin/pandoc-include", line 8, in <module>
    sys.exit(main())
             ^^^^^^
  File "/root/.local/pipx/venvs/pandoc-include/lib/python3.11/site-packages/pandoc_include/main.py", line 429, in main
    return pf.run_filter(action, doc=doc)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/root/.local/pipx/venvs/pandoc-include/lib/python3.11/site-packages/panflute/io.py", line 227, in run_filter
    return run_filters([action], *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/root/.local/pipx/venvs/pandoc-include/lib/python3.11/site-packages/panflute/io.py", line 208, in run_filters
    doc = doc.walk(action, doc=doc, stop_if=stop_if)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/root/.local/pipx/venvs/pandoc-include/lib/python3.11/site-packages/panflute/base.py", line 264, in walk
    child = child.walk(action, doc, stop_if)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/root/.local/pipx/venvs/pandoc-include/lib/python3.11/site-packages/panflute/containers.py", line 86, in walk
    ans = list(chain.from_iterable(ans))
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/root/.local/pipx/venvs/pandoc-include/lib/python3.11/site-packages/panflute/containers.py", line 84, in <genexpr>
    ans = ((item,) if type(item) is not list else item for item in ans)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/root/.local/pipx/venvs/pandoc-include/lib/python3.11/site-packages/panflute/containers.py", line 82, in <genexpr>
    ans = (item.walk(action, doc, stop_if) for item in self)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/root/.local/pipx/venvs/pandoc-include/lib/python3.11/site-packages/panflute/base.py", line 272, in walk
    altered = action(self, doc)
              ^^^^^^^^^^^^^^^^^
  File "/root/.local/pipx/venvs/pandoc-include/lib/python3.11/site-packages/pandoc_include/main.py", line 336, in action
    new_doc = pf.convert_text(
              ^^^^^^^^^^^^^^^^
  File "/root/.local/pipx/venvs/pandoc-include/lib/python3.11/site-packages/panflute/tools.py", line 487, in convert_text
    out = inner_convert_text(text, in_fmt, out_fmt, extra_args, pandoc_path=pandoc_path)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/root/.local/pipx/venvs/pandoc-include/lib/python3.11/site-packages/panflute/tools.py", line 510, in inner_convert_text
    out = run_pandoc(text, args, pandoc_path=pandoc_path)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/root/.local/pipx/venvs/pandoc-include/lib/python3.11/site-packages/panflute/tools.py", line 408, in run_pandoc
    raise IOError('')
OSError
Error running filter /root/.local/bin/pandoc-include:
Filter returned error status 1
```

`pipx` installs the executable in `/root/.local/bin/` folder and I'm referencing to this folder.

**Comment by kingkaos** [comment]
Solved it.

As mentioned in the `readme`, `pandoc-include` folder must be in the `$PATH` variable. So I just appended the default `pipx` bin folder to `PATH`.
