### ISSUE TITLE
newlines in src do not work

### ISSUE THREAD

**Issue by towi** [DCsunset/pandoc-include#37]
When my included source code contained a newline I got a backtrace:

```
Traceback (most recent call last):
  File "/usr/bin/pandoc-include", line 8, in <module>
    sys.exit(main())
  File "/usr/lib/python3.10/site-packages/pandoc_include/main.py", line 333, in main
    return pf.run_filter(action, doc=doc)
...
  File "/usr/lib/python3.10/site-packages/pandoc_include/main.py", line 309, in action
    codes.append(read_file(fn, config))
  File "/usr/lib/python3.10/site-packages/pandoc_include/main.py", line 160, in read_file
    content = "\n".join(dedent(content, config["dedent"]))
TypeError: sequence item 4: expected str instance, NoneType found
Error running filter pandoc-include:
Filter returned error status 1
```

I fixed this by adding a check in `removeLeadingWhitespaces()`:

```
def removeLeadingWhitespaces(s, num):
    if not s.strip():  # <<< empty lines didn't work
        return s
    regex = re.compile(r"[^\s]")
    m = regex.search(s)
    if m == None:
        return
    pos = m.span()[0]
    if num < 0:
        return s[pos:]
    else:
        return s[min(pos, num):]
```

**Comment by DCsunset** [comment]
Hi, I'm using a cpp file with only a newline in it and include it in another file simply like the following:

    ```cpp
    !include empty.cpp
    ```

But I'm able to reproduce this error.  Could you provide a minimum test case?

**Comment by alcuinus** [comment]
I am trying to run the example file provided in the project homepage and I get this error:

```
Traceback (most recent call last):
  File "/home/NAME/.local/bin/pandoc-include", line 8, in <module>
    sys.exit(main())
  File "/home/NAME/.local/lib/python3.10/site-packages/pandoc_include/main.py", line 333, in main
    return pf.run_filter(action, doc=doc)
  File "/home/NAME/.local/lib/python3.10/site-packages/panflute/io.py", line 227, in run_filter
    return run_filters([action], *args, **kwargs)
  File "/home/NAME/.local/lib/python3.10/site-packages/panflute/io.py", line 200, in run_filters
    doc = load(input_stream=input_stream)
  File "/home/NAME/.local/lib/python3.10/site-packages/panflute/io.py", line 58, in load
    doc = json.load(input_stream, object_hook=from_json)
  File "/usr/lib/python3.10/json/__init__.py", line 293, in load
    return loads(fp.read(),
  File "/usr/lib/python3.10/json/__init__.py", line 359, in loads
    return cls(**kw).decode(s)
  File "/usr/lib/python3.10/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/lib/python3.10/json/decoder.py", line 353, in raw_decode
    obj, end = self.scan_once(s, idx)
  File "/home/NAME/.local/lib/python3.10/site-packages/panflute/elements.py", line 1413, in from_json
    return Doc(*items, api_version=api, metadata=meta)
  File "/home/NAME/.local/lib/python3.10/site-packages/panflute/elements.py", line 66, in __init__
    raise TypeError("invalid api version", api_version)
TypeError: ('invalid api version', [1, 20])
Error running filter pandoc-include:
Filter returned error status 1
```
The installation is local (I edited the real folder name for security). The problem seems to be an invalid api version; I am almost illiterate insofar as Python is concerned and I ask your kind help. Pandoc version: 2.9.2.1-3ubuntu2. I am on Linux Mint 21. This filter looks excellent and I would really like to be able to use it.
Thank you.
